// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWPM5UtrBaI0dZk3CtPazD1amji92znUQ',
    appId: '1:232008737333:web:caf0780b398a788bce477c',
    messagingSenderId: '232008737333',
    projectId: 'flutterproject-11d18',
    authDomain: 'flutterproject-11d18.firebaseapp.com',
    storageBucket: 'flutterproject-11d18.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy-hH-9cMCTqggRmnsny1RKPARAEG8TQY',
    appId: '1:232008737333:android:456be97c36e4427dce477c',
    messagingSenderId: '232008737333',
    projectId: 'flutterproject-11d18',
    storageBucket: 'flutterproject-11d18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPMjpGCkogllk_uUo4EMl-C2MfhDfABgk',
    appId: '1:232008737333:ios:edecfe9aedaeae2dce477c',
    messagingSenderId: '232008737333',
    projectId: 'flutterproject-11d18',
    storageBucket: 'flutterproject-11d18.firebasestorage.app',
    iosBundleId: 'com.example.introMobileFlutter',
  );
}
